# Generated by Django 4.1.1 on 2022-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent_off',
            field=models.IntegerField(verbose_name='Процент скидки'),
        ),
    ]
