# Generated by Django 4.1.1 on 2023-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_discount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название купона'),
        ),
    ]
