# Generated by Django 4.1.1 on 2022-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('ru', 'RUB'), ('us', 'USD')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
