# Generated by Django 4.1.1 on 2022-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_total_price_alter_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='orders', to='shop.item', verbose_name='Товары'),
        ),
    ]
