# Generated by Django 4.1.1 on 2023-02-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_discount_options'),
        ('shop', '0020_alter_item_options_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.discount', verbose_name='Скидка'),
        ),
    ]
