# Generated by Django 4.1.1 on 2023-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Товар оплачен'),
        ),
    ]
