# Generated by Django 4.1.1 on 2023-12-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
